# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientreg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3
conn = sqlite3.connect('Users.db')
class Ui_RegisterClient(object):

    def successful(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Data Saved Successfuly")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    def owner(self):
        while 1:
            with open('is_logedin.txt') as f:
                data = [line.split() for line in f.readlines()]
                for i in data:
                    self.lguser = i[0]
                return self.lguser

    def idgenerator(self):
        result = conn.execute("SELECT max(name_id) FROM clientsreg")
        data = result.fetchall()
        myList = data[0]
        currlt = myList[0]
        newid = currlt + 1
        return newid
        # print(newid)

    def InsertData(self):
        name_id = self.idgenerator()
        c_name = self.lineEdit.text()
        mobile_no = self.lineEdit_3.text()
        pan_no = self.lineEdit_2.text()
        GSTN = self.lineEdit_4.text()
        dob = self.dateEdit.text()
        it_paswd = self.lineEdit_7.text()
        tan = self.lineEdit_6.text()
        traces = self.lineEdit_8.text()
        gstn_paswd = self.lineEdit_9.text()
        owner = self.owner()
        conn.execute("INSERT INTO clientsreg VALUES (?,?,?,?,?,?,?,?,?,?,?)", (
        name_id, c_name, mobile_no, pan_no, GSTN, dob, it_paswd, tan, traces,
        gstn_paswd, owner))
        conn.commit()
        def InsertAdata(name_id):
            name_id = name_id
            Description = self.lineEdit_10.text()
            Data = self.lineEdit_5.text()
            conn.execute("INSERT INTO otherinfo VALUES (?,?,?)", (Description, Data, name_id))
            conn.commit()
        InsertAdata(name_id)
        self.successful()


    def setupUi(self, RegisterClient):
        RegisterClient.setObjectName("RegisterClient")
        RegisterClient.resize(741, 325)
        self.regtabWidget = QtWidgets.QTabWidget(RegisterClient)
        self.regtabWidget.setGeometry(QtCore.QRect(0, 10, 741, 271))
        self.regtabWidget.setObjectName("regtabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formWidget = QtWidgets.QWidget(self.tab)
        self.formWidget.setGeometry(QtCore.QRect(300, 30, 301, 171))
        self.formWidget.setObjectName("formWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.clname = QtWidgets.QLabel(self.formWidget)
        self.clname.setObjectName("clname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clname)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.clname_2 = QtWidgets.QLabel(self.formWidget)
        self.clname_2.setObjectName("clname_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.clname_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.clname_3 = QtWidgets.QLabel(self.formWidget)
        self.clname_3.setObjectName("clname_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.clname_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.clname_4 = QtWidgets.QLabel(self.formWidget)
        self.clname_4.setObjectName("clname_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.clname_4)
        self.label_2 = QtWidgets.QLabel(self.formWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(60, 40, 181, 91))
        self.label.setStyleSheet("image: url(:/tst-imgs/information.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.formWidget.raise_()
        self.label.raise_()
        self.regtabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formWidget_2.setGeometry(QtCore.QRect(40, 20, 301, 171))
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.clname_5 = QtWidgets.QLabel(self.formWidget_2)
        self.clname_5.setObjectName("clname_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clname_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.clname_6 = QtWidgets.QLabel(self.formWidget_2)
        self.clname_6.setObjectName("clname_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.clname_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.clname_7 = QtWidgets.QLabel(self.formWidget_2)
        self.clname_7.setObjectName("clname_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.clname_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.clname_8 = QtWidgets.QLabel(self.formWidget_2)
        self.clname_8.setObjectName("clname_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.clname_8)
        self.label_3 = QtWidgets.QLabel(self.formWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(self.formWidget_2)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(460, 30, 231, 141))
        self.label_4.setStyleSheet("image: url(:/tst-imgs/tax.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.regtabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.formWidget_3.setGeometry(QtCore.QRect(20, 40, 301, 141))
        self.formWidget_3.setObjectName("formWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formWidget_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.formWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formWidget_3)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.clname_12 = QtWidgets.QLabel(self.formWidget_3)
        self.clname_12.setObjectName("clname_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.clname_12)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formWidget_3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.clname_9 = QtWidgets.QLabel(self.formWidget_3)
        self.clname_9.setObjectName("clname_9")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.clname_9)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(370, -40, 381, 301))
        self.label_6.setStyleSheet("image: url(:/tst-imgs/gst.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.regtabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(70, 20, 391, 41))
        self.label_7.setObjectName("label_7")
        self.gridWidget = QtWidgets.QWidget(self.tab_4)
        self.gridWidget.setGeometry(QtCore.QRect(40, 100, 531, 61))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.regtabWidget.addTab(self.tab_4, "")
        self.pushButton = QtWidgets.QPushButton(RegisterClient)
        self.pushButton.setGeometry(QtCore.QRect(550, 290, 85, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.InsertData)
        self.pushButton_2 = QtWidgets.QPushButton(RegisterClient)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 290, 85, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(RegisterClient.close)

        self.retranslateUi(RegisterClient)
        self.regtabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(RegisterClient)

    def retranslateUi(self, RegisterClient):
        _translate = QtCore.QCoreApplication.translate
        RegisterClient.setWindowTitle(_translate("RegisterClient", "RegisterClient"))
        self.lineEdit.setText(_translate("RegisterClient", "Enter Name"))
        self.clname.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">Client Name </span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("RegisterClient", "Enter PAN Number"))
        self.clname_2.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">PAN No</span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.lineEdit_3.setText(_translate("RegisterClient", "Enter Mobile Number"))
        self.clname_3.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">Mobile No </span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.lineEdit_4.setText(_translate("RegisterClient", "Enter GSTN"))
        self.clname_4.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">GSTN </span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.label_2.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" color:#ff0000;\">(fields marked * are Mandatory)</span></p></body></html>"))
        self.regtabWidget.setTabText(self.regtabWidget.indexOf(self.tab), _translate("RegisterClient", "General Information"))
        self.clname_5.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">DOB </span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.lineEdit_6.setText(_translate("RegisterClient", "Enter PAN Number"))
        self.clname_6.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">TAN </span></p></body></html>"))
        self.lineEdit_7.setText(_translate("RegisterClient", "Enter Income Tax Password"))
        self.clname_7.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">Password </span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.lineEdit_8.setText(_translate("RegisterClient", "Enter TRACES p/w"))
        self.clname_8.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">TRACES </span></p></body></html>"))
        self.label_3.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" color:#ff0000;\">(fields marked * are Mandatory)</span></p></body></html>"))
        self.regtabWidget.setTabText(self.regtabWidget.indexOf(self.tab_2), _translate("RegisterClient", "IncomeTax"))
        self.label_5.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" color:#ff0000;\">(fields marked * are Mandatory)</span></p></body></html>"))
        self.lineEdit_11.setText(_translate("RegisterClient", "Enter GSTN"))
        self.clname_12.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">GSTN </span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.lineEdit_9.setText(_translate("RegisterClient", "Enter GST Password"))
        self.clname_9.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-weight:600;\">Password </span><span style=\" font-weight:600; color:#ff0000;\">*</span></p></body></html>"))
        self.regtabWidget.setTabText(self.regtabWidget.indexOf(self.tab_3), _translate("RegisterClient", "GST"))
        self.label_7.setText(_translate("RegisterClient", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#0055ff;\">Any additional Informations you can add here.......</span></p></body></html>"))
        self.label_8.setText(_translate("RegisterClient", "Description"))
        self.lineEdit_5.setText(_translate("RegisterClient", "Enter Data"))
        self.label_9.setText(_translate("RegisterClient", "Data"))
        self.lineEdit_10.setText(_translate("RegisterClient", "Enter Description "))
        self.regtabWidget.setTabText(self.regtabWidget.indexOf(self.tab_4), _translate("RegisterClient", "Others"))
        self.pushButton.setText(_translate("RegisterClient", "Save"))
        self.pushButton_2.setText(_translate("RegisterClient", "Close"))

import imgs

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterClient = QtWidgets.QWidget()
    ui = Ui_RegisterClient()
    ui.setupUi(RegisterClient)
    RegisterClient.show()
    sys.exit(app.exec_())

